name = "artistic-weather-forecast"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "e2b2e18c60bca9c5eb2578151d9c392e"

[vars]
CLOUDFLARE_ACCOUNT_ID = "e2b2e18c60bca9c5eb2578151d9c392e"

# Secrets (set via wrangler secret put):
# - OPENWEATHER_API_KEY
# - GEMINI_API_KEY
# - CLOUDFLARE_API_TOKEN

[ai]
binding = "AI"

